version: '3.0'
services:
  test_db:
    container_name: 'test_db'
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_db"
      POSTGRES_PASSWORD: "12345"
    ports:
      - '6000:5432'