name: GitHub-actions-Basic

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    repos:
      - repo: https://github.com/pre-commit/mirrors-autopep8
        rev: v2.0.1
        hooks:
          - id: autopep8
            args: [ "-i", "--in-place", "--max-line-length=120" ]
      - repo: https://github.com/psf/black
        rev: 23.1.0
        hooks:
          - id: black
            language_version: python3.11
            args: [ "--line-length=120" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run black --check .
        run:
          poetry run black .
      - name: Run flake8
        run:
          poetry run flake8 .
      - name: Run isort
        run:
          poetry run isort .

